### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by kazuser** [pchemguy/SQLite-ICU-MinGW#1]
Finally someone decided to do it!

Thank you 👍

**Comment by pchemguy** [comment]
Would you elaborate on what specifically you are excited about? To clarify, I am not working on the SQLiteODBC driver itself. Just the building process.

**Comment by kazuser** [comment]
I mean that the assembly process _for Windows_ will finally be simplified as much as possible. Still can't find a normal guide so far: either something doesn’t work all the time, or it’s completely outdated. That's why I'm so glad ;)

**Comment by pchemguy** [comment]
I see. I had a similar feeling. Please check out project [documentation](https://pchemguy.github.io/SQLite-ICU-MinGW/) and try it out. Worked out most issues locally, had to apply some workarounds occasionally. But I cannot improve it beyond a certain level without feedback.
